Made some changes on travis.yml file

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -44,21 +44,21 @@ before_script:
   - ./scripts/travis/couch-config
   - ./scripts/travis/yarn-init
 
-# script:
-#   - |
-#     if [[ "$TEST_SUITE" = 'normal' ]]; then
-#       node --stack_size=10000 `which grunt` ci-unit &&
-#       node --stack_size=10000 `which grunt` ci-integration-e2e
-#     elif [[ "$TEST_SUITE" = 'performance' ]]; then
-#       node --stack_size=10000 `which grunt` ci-performance
-#     elif [[ "$TEST_SUITE" = 'standard' ]]; then
-#       cd config/standard &&
-#       npm install &&
-#       npm run travis
-#     else
-#       echo "ERROR No or unknown value for TEST_SUITE env var ('${TEST_SUITE}')."
-#       exit 1
-#     fi
+script:
+  - |
+    if [[ "$TEST_SUITE" = 'normal' ]]; then
+      node --stack_size=10000 `which grunt` ci-unit &&
+      node --stack_size=10000 `which grunt` ci-integration-e2e
+    elif [[ "$TEST_SUITE" = 'performance' ]]; then
+      node --stack_size=10000 `which grunt` ci-performance
+    elif [[ "$TEST_SUITE" = 'standard' ]]; then
+      cd config/standard &&
+      npm install &&
+      npm run travis
+    else
+      echo "ERROR No or unknown value for TEST_SUITE env var ('${TEST_SUITE}')."
+      exit 1
+    fi
 
 jobs:
   include:
